### ISSUE TITLE
自动化测试流程，并提供覆盖率报告

### ISSUE THREAD

**Issue by Soulter** [Soulter/AstrBot#180]
# Todos

- [x] Mock QQ 官方机器人 API 的 `botpy.message.GroupMessage`, `botpy.message.Message`, `botpy.message.DirectMessage` 接口。
- [x] Mock OneBot 协议
- [x] OpenAI LLM Handler 测试
- [ ] AstrBot 更新器测试
- [ ] AstrBot 插件更新器测试
- [x] 其他通用指令测试
- [x] AstrBot 可视化面板 Web 接口 Mock
